<html>
<body>
Сообщает о вызове <code>Throwable.initCause()</code>, когда конструктор исключения также включает параметр <code>Throwable cause</code>.
<p>В этом случае вызов <code>initCause()</code> можно удалить, а его аргумент добавить в вызов конструктора исключения.</p>
<p><b>Пример:</b></p>
<pre><code>
  try {
      process();
  }
  catch (RuntimeException ex) {
    RuntimeException wrapper = new RuntimeException("Error while processing");
    wrapper.initCause(ex); // Ненужный вызов 'Throwable.initCause()'
    throw wrapper;
  }
</code></pre>
<p>Аргумент cause можно передать в конструктор с помощью быстрого исправления. После применения быстрого исправления:</p>
<pre><code>
  try {
      process();
  }
  catch (RuntimeException ex) {
    RuntimeException wrapper = new RuntimeException("Error while processing", ex);
    throw wrapper;
  }
  </code></pre>
</body>
</html>
